### PR TITLE
Add querystring parameters to pagination creation

### PR DESCRIPTION
**Pull request by ZAlfonse**
Small change to allow for querystring parameters to be carried over when calculating pagination

### CODE REVIEW

**Comment by arianamiri** [comment]
Looks good but needs tests.

**Comment by darrentorpey** [comment]
:+1: for early merge if you've manually tested, but not done until automated tests are added

**Comment by nsheaps** [comment]
Why does this break the travis build?

**Comment by arianamiri** [comment]
This feature needs tests, and we also need to fix the existing test before merging.

**Pull request merged**
